# Site settings
title: "Yoni Shpund Resume"
# description: "You can add here description of the page"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Yoni Shpund"
resume_title:                   "Software Engineer & Team Lead"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "shpundyoni@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+972-54-5317440"
resume_contact_address:         "Holon, Israel"

resume_header_contact_info:     "Holon, Israel • +972-54-5317440 • shpundyoni@gmail.com"
display_header_contact_info:    "true"

# This is the executive summary. You should write a few brief, concise, 
# and meaningful sentences about yourself from a professional context, and your immediate career goals. 
# Make the length appropriate for your needs, but keep it brief and concise
resume_header_intro: "<p>Wireless and RF software engineer, have developed numerous advanced systems in Java, C, HTML, JavaScript, JQuery, AngularJS, Python and ASP.NET. 
Experienced in building Desktop, WEB, and embedded applications for both Linux and Windows operating systems.</p>"

# Use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove/comment the resume_looking_for_work option entirely to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

information:
  experience:
    - company: "Mobilicom"
      position: "Software Engineer & Team Lead"
      duration: "Oct 2019 – Present"
      summary: "• Manage a team of 3 Senior Developers, with agile methodology, to effectively execute 5 projects with 100% on-time delivery while achieving a cost-reduction of 20%.\n• Participating in the recruitment process.\n• Write software designs.\n\n• C - Developing client-side libraries across the system to reduce additional costs involved in using third-party libraries\n• Linux - Research the Linux kernel of the system and add functionalities to harden it and make it more compatible with a real-time system, using kernel configuration and ARM compilation flags.\n• Python – Gathered and defined customer requirements to develop clear specifications for creating well-organized project plans to help to reduce the time for QA testing by 60%. Manage a developer and participating in building the system.\n• Java + Web Applications - Continue development and maintenance.\n\n• Scripts/UI: JavaScript, JQuery, Python, Bash/Shell\n• Versioning and other tools: Git, SVN, Jira, OpenVPN\n• Development Environments: NetBeans, Eclipse, VS Code."


# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/YoniShpund"
  # resume_twitter_url:           "insert twitter URL here"
  # resume_dribbble_url:          "insert dribbble URL here"
  # resume_facebook_url:          "insert facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yoni-shpund/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "insert website URL here"
  # resume_medium_url:            "insert medium URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
