# Site settings
title: "Yoni Shpund Resume"
# description: "You can add here description of the page"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Yoni Shpund"
resume_title:                   "Software Engineer & Team Lead"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "shpundyoni@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+972-54-5317440"
resume_contact_address:         "Holon, Israel"

resume_header_contact_info:     "Holon, Israel • +972-54-5317440 • shpundyoni@gmail.com"
display_header_contact_info:    "true"

# This is the executive summary. You should write a few brief, concise, 
# and meaningful sentences about yourself from a professional context, and your immediate career goals. 
# Make the length appropriate for your needs, but keep it brief and concise
resume_header_intro: "<p>Wireless and RF software engineer, have developed numerous advanced systems in Java, C, HTML, JavaScript, JQuery, AngularJS, Python and ASP.NET. 
Experienced in building Desktop, WEB, and embedded applications for both Linux and Windows operating systems.</p>"

# Use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove/comment the resume_looking_for_work option entirely to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
