# Site settings
title: "Yoni Shpund Resume"
# description: "You can add here description of the page"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  true
resume_name:                    "Yoni Shpund"
resume_title:                   "Software Engineer & Team Lead"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "shpundyoni@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+972-54-5317440"
resume_contact_address:         "Holon, Israel"

resume_header_contact_info:     "Holon, Israel • +972-54-5317440 • shpundyoni@gmail.com"
display_header_contact_info:    true

# This is the executive summary. You should write a few brief, concise, 
# and meaningful sentences about yourself from a professional context, and your immediate career goals. 
# Make the length appropriate for your needs, but keep it brief and concise
resume_header_intro: "Wireless and RF software engineer, have developed numerous advanced systems in Java, C, HTML, JavaScript, JQuery, AngularJS, and Python.<br>
Experienced in building Desktop, WEB, and embedded applications for both Linux and Windows operating systems."

# Use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove/comment the resume_looking_for_work option entirely to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

information:
  experience:
    # Start of Experience
    - company: "Mobilicom"
      position: "Software Engineer & Team Lead"
      duration: "Oct 2019 – Present"
      summary: "• Manage a team of 3 Senior Developers, with agile methodology, to effectively execute 5 projects with 100% on-time delivery while achieving a cost-reduction of 20%.<br>• Participating in the recruitment process.<br>• Write software designs.<br><br>• C - Developing client-side libraries across the system to reduce additional costs involved in using third-party libraries<br>• Linux - Research the Linux kernel of the system and add functionalities to harden it and make it more compatible with a real-time system, using kernel configuration and ARM compilation flags.<br>• Python – Gathered and defined customer requirements to develop clear specifications for creating well-organized project plans to help to reduce the time for QA testing by 60%. Manage a developer and participating in building the system.<br>• Java + Web Applications - Continue development and maintenance.<br><br>• Scripts/UI: JavaScript, JQuery, Python, Bash/Shell<br>• Versioning and other tools: Git, SVN, Jira, OpenVPN<br>• Development Environments: NetBeans, Eclipse, VS Code."
      link:
        - "https://www.skyhopper.biz/products/controlling-systems/"
        - "https://www.skyhopper.biz/products/video-processing-analytics/"
    - company: "Mobilicom"
      position: "Junior Software Engineer"
      duration: "Jul 2019 – Oct 2019"
      summary: "• AngularJS, JQuery – Integrate AngularJS and JQuery into a working system and improve the efficiency of the whole WEB application by 40%, using JSON objects, and HTTP communication protocol.<br>• Java - Implement an internal database that manages the supplies of the company along with a desktop application that runs it.<br>• C, HTML + CSS, JavaScript - Continue all the development and support from my internship.<br><br>• Scripts/UI: JavaScript, JQuery, Bash/Shell<br>• Versioning and other tools: Git, SVN<br>• Development Environments: NetBeans, Eclipse."
    - company: "Mobilicom"
      position: "Software Engineer Intern"
      duration: "Aug 2017 – Jul 2019"
      summary: "• Java - Create, from scratch, a multithreaded application, that uses TCP/IP communication, to allow the ability to control the Mesh network. Research and integrate with the OSM API to help the user see the whole Mesh updated on the map, using the GPS location of the devices.<br>• C, HTML + CSS, JavaScript - Create web and embedded applications that communicate using the HTTP and TCP/IP protocols to deliver information and configuration to and from the user.<br>• Evaluated project requirements and specifications and developed software applications that surpassed client expectations.<br><br>• Scripts/UI: JavaScript, Bash/Shell<br>• Versioning and other tools: Git, SVN<br>• Development Environments: NetBeans, Eclipse."
      link:
        - "https://www.mobilicom.com/mobilicom-software-management-solutions"
        - "https://www.mobilicom.com/mobilicom-element-management-application-solution-mc-ema-0"
    - company: "Aplit-Soft"
      position: "Software Engineer Intern"
      duration: "May 2016 – Jun 2017"
      summary: "• Designed a web page that communicates with a server using the HTTP protocol.<br>The page displays information from a connected device.<br>• QA - Test software, report defects and investigate the root cause as well as finding solutions.<br>• C# - Create a test application that checks the maximal capabilities of the hardware.<br>"
    - company: "Israel Defence Forces"
      position: "Operations Department Sergeant"
      duration: "Mar 2012 – Mar 2015"
      summary: "• Managed a group of 10 soldiers to achieve maximum efficiency on the field.<br>• Assessed ongoing risk factors and suggested improvements to senior management.<br>• Recorded incident reports with detailed accounts of occurrences.<br>• Developed improved training methods with a focus on public safety and officer awareness."
    # End of Experience

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/YoniShpund"
  # resume_twitter_url:           "insert twitter URL here"
  # resume_dribbble_url:          "insert dribbble URL here"
  # resume_facebook_url:          "insert facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yoni-shpund/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "insert website URL here"
  # resume_medium_url:            "insert medium URL here"
resume_print_social_links:      true

# Design settings - set to default to use Google's font
# resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
# 
# To run the server locally run this command (from the root directory):
# bundle exec jekyll serve
